### ISSUE TITLE
ampl cell magic is not working

### ISSUE THREAD

**Issue by JulianaCrespo** [vitaut/iampl#3]
I was trying this package, but every time I enter the magic command I get the follwoing error message:
ERROR: Cell magic `%%ampl` not found.

**Comment by vitaut** [comment]
You need to load the extension after installing it:
```
%load_ext ampl
```

I've added this information to the [Usage](https://github.com/vitaut/iampl/blob/master/README.rst#usage) section of the readme.

Cheers!
